# This is a basic workflow to help you get started with Actions

name: React -> GH Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Build React App
        run: |
          cd $GITHUB_WORKSPACE
          npm i
          npm run build
      - name: Deploy to GH Pages
        run: |
          cd $GITHUB_WORKSPACE/dist
          git init
          git add .
          git commit -m "Auto-Deploy"
          git push --force --quiet "https://github.com/FutureDeveloperZ/Obama-site" master:gh-pages
          
          
